import "../globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";

import AuthModals from "@/components/auth/AuthModals";
import ContentWrapper from "@/components/ContentWrapper"; // Client-side content wrapper
import Navbar from "@/components/navigation/Navbar";
import Footer from "@/components/sections/Footer";
import Providers from "@/context/Providers"; // Centralized Providers

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <Providers>
          <Navbar />
          {/* Conditionally render the page content */}
          <div className="absolute top-0 min-h-screen overflow-y-hidden max-lg:hidden flex">
            <AuthModals />
          </div>
          <ContentWrapper>{children}</ContentWrapper>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
